app:
    resource: "@AppBundle/Controller/"
    type:     annotation

category:
    type: rest
    resource: AppBundle\Controller\CategoryController

products:
    type: rest
    resource: AppBundle\Controller\ProductsController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin